In [57]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [59]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [60]:
df.shape

(569, 33)

In [63]:
df.drop(columns = ["id", "Unnamed: 32"], inplace = True)

In [65]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [67]:
x_train, x_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [69]:
scaler = StandardScaler()

In [71]:
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [73]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [75]:
y_train

array([0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0,
       0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1,

In [77]:
x_train

array([[ 0.55140219, -0.71883087,  0.56538831, ...,  0.15830341,
         0.41827593,  0.29923772],
       [-0.14458358, -0.71883087, -0.18866806, ..., -0.68877362,
         0.69952881, -0.38361352],
       [ 1.46909309, -0.07868943,  1.45587741, ...,  1.39908798,
         0.60522637,  0.32581413],
       ...,
       [-0.75357112, -0.98419859, -0.75931635, ..., -0.28678396,
        -0.39073969, -0.32503693],
       [-0.41680382, -1.2518941 , -0.43620769, ..., -0.7875456 ,
        -0.87879616, -0.80612434],
       [-0.82934377, -1.0191154 , -0.86102818, ..., -1.50471601,
        -0.14092096, -0.5371059 ]])

In [79]:
x_train_tensor = torch.from_numpy(x_train)
x_test_tensor = torch.from_numpy(x_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [81]:
x_train_tensor = x_train_tensor.float()
y_train_tensor = y_train_tensor.float()
x_test_tensor = x_test_tensor.float()
y_test_tensor = y_test_tensor.float()

In [83]:
x_train_tensor.dtype

torch.float32

In [85]:
class CustomDataset(Dataset):
    def __init__(self, features, labels):
        self.features = features
        self.labels = labels

    def __len__(self):
        return self.features.shape[0]

    def __getitem__(self, index):
        return self.features[index], self.labels[index]

In [87]:
train_dataset = CustomDataset(x_train_tensor, y_train_tensor)
test_dataset = CustomDataset(x_test_tensor, y_test_tensor)

In [89]:
train_dataset[10]

(tensor([ 0.0378, -1.3241,  0.0021, -0.0607,  0.1981, -0.5396, -0.4040, -0.0837,
          0.9933, -1.1661,  0.4279, -0.6884,  0.4600,  0.1764,  0.0359, -0.6174,
         -0.2653,  0.1902,  0.2836, -0.8433,  0.0790, -1.4007,  0.0739, -0.0370,
         -0.1148, -0.6497, -0.5275, -0.0932,  0.2677, -1.2671]),
 tensor(0.))

In [93]:
train_loader = DataLoader(train_dataset, batch_size=32, shuffle = True)
test_loader = DataLoader(test_dataset, batch_size = 32, shuffle = True)

In [95]:
import torch
import torch.nn as nn

In [97]:
class MySimpleNN(nn.Module):

    def __init__(self, num_features):
        super().__init__()
        self.linear = nn.Linear(num_features, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, features):
        out = self.linear(features)
        out = self.sigmoid(out)
        return out

    

In [99]:
learning_rate = 0.1
epochs = 25

In [101]:
loss_function = nn.BCELoss()

In [195]:
model = MySimpleNN(x_train_tensor.shape[1])
optimizer = torch.optim.SGD(model.parameters(), lr = learning_rate)

for batch_features, batch_labels in train_loader:
    # Forward pass
    y_pred = model(batch_features)
    # Loss Calculate
    loss = loss_function(y_pred, batch_labels.view(-1,1))

    optimizer.zero_grad()
    # Backward pass
    loss.backward()
    # Parameter Update
    optimizer.step()

    print(f"Epoch: {epoch + 1}, Loss: {loss.item()}")

Epoch: 25, Loss: 0.6999157667160034
Epoch: 25, Loss: 0.4958347678184509
Epoch: 25, Loss: 0.4097823202610016
Epoch: 25, Loss: 0.37133651971817017
Epoch: 25, Loss: 0.30473843216896057
Epoch: 25, Loss: 0.35359543561935425
Epoch: 25, Loss: 0.25749245285987854
Epoch: 25, Loss: 0.4093109965324402
Epoch: 25, Loss: 0.2587886452674866
Epoch: 25, Loss: 0.2375987470149994
Epoch: 25, Loss: 0.347679078578949
Epoch: 25, Loss: 0.25562191009521484
Epoch: 25, Loss: 0.22385387122631073
Epoch: 25, Loss: 0.18409636616706848
Epoch: 25, Loss: 0.1417894959449768


In [197]:
model.linear.weight

Parameter containing:
tensor([[ 0.0396,  0.1843,  0.1907,  0.1132,  0.0418,  0.0907,  0.1714,  0.3008,
          0.1063, -0.0957,  0.2562,  0.0254,  0.2608,  0.2649,  0.0157, -0.1730,
          0.0284,  0.1611, -0.0313, -0.0682,  0.0674,  0.0678,  0.1465,  0.2082,
          0.0534,  0.0161,  0.3006,  0.3165,  0.0345,  0.1386]],
       requires_grad=True)

In [199]:
model.eval()
accuracy_list = []

with torch.no_grad():
    for batch_features, batch_labels in test_loader:
        y_pred = model(batch_features)
        y_pred = (y_pred > 0.5).float()
        batch_accuracy = (y_pred.view(-1) == batch_labels).float().mean().item()
        accuracy_list.append(batch_accuracy)

overall_accuracy = sum(accuracy_list)/ len(accuracy_list)
print(f"accuracy: {overall_accuracy:.4f}")

accuracy: 0.9392


### Messing around

In [3]:
from sklearn.datasets import make_classification

In [13]:
x, y = make_classification(
    n_samples = 10,
    n_features = 2,
    n_informative = 2,
    n_redundant = 0,
    n_classes = 2,
    random_state = 42
)

In [15]:
x

array([[ 1.06833894, -0.97007347],
       [-1.14021544, -0.83879234],
       [-2.8953973 ,  1.97686236],
       [-0.72063436, -0.96059253],
       [-1.96287438, -0.99225135],
       [-0.9382051 , -0.54304815],
       [ 1.72725924, -1.18582677],
       [ 1.77736657,  1.51157598],
       [ 1.89969252,  0.83444483],
       [-0.58723065, -1.97171753]])

In [23]:
x = torch.tensor(x, dtype = torch.float32)
y = torch.tensor(y, dtype = torch.long)

In [25]:
x

tensor([[ 1.0683, -0.9701],
        [-1.1402, -0.8388],
        [-2.8954,  1.9769],
        [-0.7206, -0.9606],
        [-1.9629, -0.9923],
        [-0.9382, -0.5430],
        [ 1.7273, -1.1858],
        [ 1.7774,  1.5116],
        [ 1.8997,  0.8344],
        [-0.5872, -1.9717]])

In [27]:
y

tensor([1, 0, 0, 0, 0, 1, 1, 1, 1, 0])

In [33]:
from torch.utils.data import Dataset, DataLoader

In [35]:
class CostumDataset(Dataset):
    def __init__(self, features, labels):
        self.features = features
        self.labels = labels

    def __len__(self):
        return self.features.shape[0]

    def __getitem__(self, index):
        return self.features[index], self.labels[index]

In [37]:
dataset = CostumDataset(x,y)

In [39]:
len(dataset)

10

In [41]:
dataset[0]

(tensor([ 1.0683, -0.9701]), tensor(1))

In [43]:
dataloader = DataLoader(dataset, batch_size = 2, shuffle=True)

In [47]:
for batch_features, batch_labels in dataloader:
    print(batch_features)
    print(batch_labels)
    print("-"*50)

tensor([[-2.8954,  1.9769],
        [-0.9382, -0.5430]])
tensor([0, 1])
--------------------------------------------------
tensor([[-1.9629, -0.9923],
        [ 1.7273, -1.1858]])
tensor([0, 1])
--------------------------------------------------
tensor([[ 1.7774,  1.5116],
        [-0.7206, -0.9606]])
tensor([1, 0])
--------------------------------------------------
tensor([[-0.5872, -1.9717],
        [-1.1402, -0.8388]])
tensor([0, 0])
--------------------------------------------------
tensor([[ 1.8997,  0.8344],
        [ 1.0683, -0.9701]])
tensor([1, 1])
--------------------------------------------------
