In [2]:
import torch
import torch.nn as nn

In [4]:
class Model(nn.Module):
    def __init__(self, num_features):

        super().__init__()
        self.linear = nn.Linear(num_features, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, features):
        out = self.linear(features)
        out = self.sigmoid(out)

        return out

In [8]:
features = torch.rand(10, 5)

model = Model(features.shape[1])

#call forward pass
model(features)
# work same as model.forward(features)...pytorch inbuilt feature

tensor([[0.3943],
        [0.3114],
        [0.3902],
        [0.3283],
        [0.3378],
        [0.3526],
        [0.3636],
        [0.3640],
        [0.3622],
        [0.2895]], grad_fn=<SigmoidBackward0>)

In [98]:
model.linear.weight

Parameter containing:
tensor([[ 0.2652,  0.0352,  0.2531, -0.2539,  0.3610],
        [ 0.1678,  0.1502, -0.1215,  0.2617, -0.1732],
        [-0.1914,  0.0480,  0.3591, -0.3574, -0.1553]], requires_grad=True)

In [14]:
model.linear.bias

Parameter containing:
tensor([-0.2209], requires_grad=True)

In [20]:
from torchinfo import summary

summary(model, inpu_size=(10, 5))

Layer (type:depth-idx)                   Param #
Model                                    --
├─Linear: 1-1                            6
├─Sigmoid: 1-2                           --
Total params: 6
Trainable params: 6
Non-trainable params: 0

In [18]:
pip install torchinfo

Note: you may need to restart the kernel to use updated packages.


## Another Example

In [92]:
class Model(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        self.linear = nn.Linear(num_features, 3)
        self.relu = nn.ReLU()
        self.linear2 = nn.Linear(3, 1)
        self.sigmoid = nn.Sigmoid()
        
    def forward(self, features):
        out = self.linear(features)
        out = self.relu(out)
        out = self.linear2(out)
        out = self.sigmoid(out)

        return out

In [94]:
features = torch.rand(10, 5)

model = Model(features.shape[1])

model(features)

tensor([[0.4427],
        [0.4170],
        [0.4268],
        [0.4461],
        [0.4238],
        [0.4752],
        [0.4748],
        [0.4525],
        [0.4439],
        [0.4277]], grad_fn=<SigmoidBackward0>)

In [80]:
model.linear.weight

Parameter containing:
tensor([[-0.3731, -0.2961, -0.2262,  0.2509,  0.4091],
        [-0.2624, -0.1020, -0.0799,  0.0701,  0.0806],
        [-0.3211,  0.4327, -0.3129, -0.0707, -0.3959]], requires_grad=True)

In [82]:
summary(model, inpu_size=(10, 5))

Layer (type:depth-idx)                   Param #
Model                                    --
├─Linear: 1-1                            18
├─ReLU: 1-2                              --
├─Linear: 1-3                            4
├─Sigmoid: 1-4                           --
Total params: 22
Trainable params: 22
Non-trainable params: 0

## Making it easy

In [85]:
class Model(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        self.network = nn.Sequential(
            nn.Linear(num_features, 3),
            nn.ReLU(),
            nn.Linear(3, 1),
            nn.Sigmoid()
        )
        
    def forward(self, features):
        out = self.network(features)

        return out

In [87]:
features = torch.rand(10, 5)

model = Model(features.shape[1])

#call forward pass
model(features)

tensor([[0.5455],
        [0.5533],
        [0.5826],
        [0.5333],
        [0.5479],
        [0.5654],
        [0.5743],
        [0.5502],
        [0.5390],
        [0.5588]], grad_fn=<SigmoidBackward0>)