In [2]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [3]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [4]:
df.shape

(569, 33)

In [5]:
df.drop(columns = ["id", "Unnamed: 32"], inplace = True)

In [6]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [7]:
x_train, x_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [8]:
scaler = StandardScaler()

In [9]:
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [10]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [11]:
y_train

array([0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1,
       1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1,

In [12]:
x_train

array([[-1.32190463,  0.55991236, -1.30985627, ..., -1.3447938 ,
        -0.84565622,  0.43630002],
       [-0.93430101, -2.23780017, -0.94722175, ..., -1.03851607,
        -1.30781564, -0.38982653],
       [ 0.50781651,  0.92452653,  0.41687904, ..., -0.23158917,
         0.07866264,  0.02296265],
       ...,
       [-0.3403254 , -0.76298262, -0.36949913, ..., -0.14371645,
         0.77674961,  0.6435169 ],
       [-1.08624826, -0.7255863 , -1.03767936, ..., -0.26628763,
        -0.47075766,  0.70820365],
       [ 0.79237226, -0.04777791,  0.84705524, ...,  2.08990287,
         0.33882931,  0.35681207]])

In [13]:
x_train_tensor = torch.from_numpy(x_train)
x_test_tensor = torch.from_numpy(x_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [14]:
x_train_tensor = x_train_tensor.float()
y_train_tensor = y_train_tensor.float()
x_test_tensor = x_test_tensor.float()
y_test_tensor = y_test_tensor.float()

In [15]:
x_train_tensor.dtype

torch.float32

In [16]:
import torch
import torch.nn as nn

In [17]:
class MySimpleNN(nn.Module):

    def __init__(self, num_features):
        super().__init__()
        self.linear = nn.Linear(num_features, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, features):
        out = self.linear(features)
        out = self.sigmoid(out)
        return out

    

In [18]:
learning_rate = 0.1
epochs = 25

In [19]:
loss_function = nn.BCELoss()

In [77]:
model = MySimpleNN(x_train_tensor.shape[1])
optimizer = torch.optim.SGD(model.parameters(), lr = learning_rate)

for epoch in range(epochs):
    # Forward pass
    y_pred = model(x_train_tensor)
    # Loss Calculate
    loss = loss_function(y_pred, y_train_tensor.view(-1,1))

    optimizer.zero_grad()
    # Backward pass
    loss.backward()
    # Parameter Update
    optimizer.step()

    print(f"Epoch: {epoch + 1}, Loss: {loss.item()}")

Epoch: 1, Loss: 0.9724401235580444
Epoch: 2, Loss: 0.6721475720405579
Epoch: 3, Loss: 0.5148220062255859
Epoch: 4, Loss: 0.4306369125843048
Epoch: 5, Loss: 0.3780509829521179
Epoch: 6, Loss: 0.34143438935279846
Epoch: 7, Loss: 0.31412866711616516
Epoch: 8, Loss: 0.2927933633327484
Epoch: 9, Loss: 0.27555036544799805
Epoch: 10, Loss: 0.26125386357307434
Epoch: 11, Loss: 0.2491605132818222
Epoch: 12, Loss: 0.23876439034938812
Epoch: 13, Loss: 0.22970785200595856
Epoch: 14, Loss: 0.22172991931438446
Epoch: 15, Loss: 0.2146351933479309
Epoch: 16, Loss: 0.20827417075634003
Epoch: 17, Loss: 0.20253022015094757
Epoch: 18, Loss: 0.19731096923351288
Epoch: 19, Loss: 0.19254204630851746
Epoch: 20, Loss: 0.18816298246383667
Epoch: 21, Loss: 0.18412400782108307
Epoch: 22, Loss: 0.18038374185562134
Epoch: 23, Loss: 0.17690736055374146
Epoch: 24, Loss: 0.1736655980348587
Epoch: 25, Loss: 0.17063336074352264


In [79]:
model.linear.weight

Parameter containing:
tensor([[ 0.3180,  0.1463,  0.4819,  0.1233, -0.0762,  0.2987,  0.1238,  0.1485,
          0.0636, -0.0040,  0.1498, -0.0612,  0.2869,  0.0957,  0.0509,  0.0841,
         -0.1649, -0.0048, -0.0394, -0.0257,  0.1565,  0.2189,  0.3722,  0.1766,
          0.2642,  0.0760,  0.3182,  0.1260,  0.1206,  0.1469]],
       requires_grad=True)

In [81]:
with torch.no_grad():
    y_pred = model.forward(x_test_tensor)
    y_pred = (y_pred > 0.5).float()
    accuracy = (y_pred == y_test_tensor).float().mean()
    print(f"Accuracy: {accuracy.item()}")

Accuracy: 0.5467836260795593
