In [199]:
import torch

In [2]:
a = torch.ones(3)
a

tensor([1., 1., 1.])

In [14]:
float(a[1])

1.0

In [30]:
a[2] = 5.
float(a[2])

5.0

In [42]:
points = torch.zeros(6,3)
points

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [216]:
points = torch.tensor([[[4.,3.,5.], [1.,9.,2.]], [[5.,8.,7.], [4.,5.,8]]])
points

tensor([[[4., 3., 5.],
         [1., 9., 2.]],

        [[5., 8., 7.],
         [4., 5., 8.]]])

In [152]:
point = torch.tensor([[4,3,5], [1,9,2], [5,8,7], [4,5,8]])
point

tensor([[4, 3, 5],
        [1, 9, 2],
        [5, 8, 7],
        [4, 5, 8]])

In [154]:
float(points[0][1][2])

2.0

In [156]:
points.shape

torch.Size([2, 2, 3])

In [158]:
point.shape

torch.Size([4, 3])

In [160]:
points[:-1]

tensor([[[4., 3., 5.],
         [1., 9., 2.]]])

In [162]:
points[1:,0:]

tensor([[[5., 8., 7.],
         [4., 5., 8.]]])

In [164]:
img_t = torch.randn(3,5,5)

In [166]:
weights = torch.tensor([0.2126, 0.7152, 0.0722])

In [168]:
batch_t = torch.rand(2,3,5,5)

In [170]:
img_gray_naive = img_t.mean(-3)
batch_gray_naive = batch_t.mean(-3)

In [172]:
img_gray_naive.shape, batch_gray_naive.shape

(torch.Size([5, 5]), torch.Size([2, 5, 5]))

In [174]:
img_t

tensor([[[ 0.8599, -0.6675,  0.3590,  0.0870,  1.5669],
         [-0.0166, -1.6247, -0.5679, -1.0924, -0.4805],
         [ 0.3260,  0.8296, -1.6809, -0.1532, -1.7872],
         [ 0.9175, -0.0315,  0.3745, -0.3988, -0.8967],
         [-0.2082,  2.0458, -0.4996,  0.0054, -0.2686]],

        [[-2.8674,  0.7165,  0.0206,  1.5593,  0.3876],
         [-1.9798, -0.2999, -0.5184, -2.4486, -0.3666],
         [ 2.0665, -1.0965, -0.3011,  1.0020, -0.3994],
         [-0.1662, -0.6627,  1.2528, -1.9237,  0.2274],
         [-0.5747, -0.5341,  0.4410, -0.6291,  0.7684]],

        [[ 0.8631, -0.5274, -0.2939,  0.8135,  0.5224],
         [-1.2194,  0.2534,  0.4921,  0.8048, -0.3385],
         [ 0.3960, -0.1231, -0.3591,  0.2752, -0.1658],
         [-1.8677,  0.7455, -0.9212, -2.6905, -0.8903],
         [-1.1841, -1.2913,  2.1250,  0.2817, -0.6642]]])

In [176]:
img_gray_naive

tensor([[-0.3815, -0.1595,  0.0286,  0.8199,  0.8256],
        [-1.0719, -0.5571, -0.1981, -0.9121, -0.3952],
        [ 0.9295, -0.1300, -0.7804,  0.3746, -0.7842],
        [-0.3721,  0.0171,  0.2354, -1.6710, -0.5199],
        [-0.6557,  0.0735,  0.6888, -0.1140, -0.0548]])

In [178]:
points.storage()

 4.0
 3.0
 5.0
 1.0
 9.0
 2.0
 5.0
 8.0
 7.0
 4.0
 5.0
 8.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 12]

In [184]:
points_storage = points.storage()
points_storage[5]

2.0

In [186]:
points = torch.tensor([[4.,1.], [5.,3.], [2.,1.]])

In [206]:
second_point = points[2]

In [208]:
second_point.storage_offset()

4

In [210]:
second_point.size()

torch.Size([2])

In [212]:
points.storage_offset()

0

In [218]:
points.stride()

(6, 3, 1)

In [220]:
points_gpu = points.to(device = 'cuda')

In [222]:
points_gpu

tensor([[[4., 3., 5.],
         [1., 9., 2.]],

        [[5., 8., 7.],
         [4., 5., 8.]]], device='cuda:0')

In [8]:
import imageio

In [6]:
pip install imageio

Note: you may need to restart the kernel to use updated packages.


  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.


In [12]:
img_arr = imageio.imread(r"C:\Users\satya\Downloads\bobby.jpg")

C:\Users\satya\AppData\Local\Temp\ipykernel_3924\1592839461.py:1: DeprecationWarning: Starting with ImageIO v3 the behavior of this function will switch to that of iio.v3.imread. To keep the current behavior (and make this warning disappear) use `import imageio.v2 as imageio` or call `imageio.v2.imread` directly.
  img_arr = imageio.imread(r"C:\Users\satya\Downloads\bobby.jpg")


In [16]:
img_arr.shape

(720, 1280, 3)

In [21]:
img = torch.from_numpy(img_arr)

In [24]:
out = img.permute(2,0,1)

In [30]:
img.shape

torch.Size([720, 1280, 3])

In [6]:
torch.cuda.is_available()

True

In [4]:
t_c = [0.5, 14.0, 15.0, 28.0, 11.0, 8.0, 3.0,-4.0, 6.0, 13.0, 21.0]
t_u = [35.7, 55.9, 58.2, 81.9, 56.3, 48.9, 33.9, 21.8, 48.4, 60.4, 68.4]
t_c = torch.tensor(t_c)
t_u = torch.tensor(t_u)

In [6]:
import matplotlib.pyplot as plt

ModuleNotFoundError: No module named 'matplotlib'

In [8]:
pip install matplotlib.pyplot

Note: you may need to restart the kernel to use updated packages.


ERROR: Could not find a version that satisfies the requirement matplotlib.pyplot (from versions: none)
ERROR: No matching distribution found for matplotlib.pyplot


In [10]:
def model(t_u, w, b):
    return w * t_u +b

In [12]:
def loss_fn(t_p, t_c):
    squared_diffs = (t_p - t_c)**2
    return squared_diffs.mean()

In [14]:
w = torch.ones(())
b = torch.zeros(())

In [16]:
t_p = model(t_u, w, b)
t_p

tensor([35.7000, 55.9000, 58.2000, 81.9000, 56.3000, 48.9000, 33.9000, 21.8000,
        48.4000, 60.4000, 68.4000])

In [18]:
loss = loss_fn(t_p, t_c)
loss

tensor(1763.8848)

In [22]:
delta = 0.1 #learning rate

In [24]:
loss_rate_of_change_w = (loss_fn(model(t_u, w + delta, b), t_c) - loss_fn(model(t_u, w - delta, b), t_c)) / (2.0 * delta)

## Autograd

In [201]:
x = torch.tensor(3.0, requires_grad=True)

In [203]:
y = x**2

In [205]:
y

tensor(9., grad_fn=<PowBackward0>)

In [207]:
z = torch.sin(y)

In [209]:
z.backward()

In [211]:
x.grad

tensor(-5.4668)

In [225]:
x.grad

tensor(-5.4668)

In [75]:
x = torch.tensor(6.7)
y = torch.tensor(0.0)

In [67]:
w = torch.tensor(1.0, requires_grad = True)
w

tensor(1., requires_grad=True)

In [69]:
b = torch.tensor(0.0, requires_grad = True)
b

tensor(0., requires_grad=True)

In [71]:
z = w * x  +  b

In [81]:
y_pred = torch.sigmoid(z)
y_pred

tensor(0.9988, grad_fn=<SigmoidBackward0>)

In [89]:
loss = binary_cross_entropy_loss(y_pred, y)
loss

tensor(6.7012, grad_fn=<NegBackward0>)

In [85]:
def binary_cross_entropy_loss(prediction, target):
    epsilon = 1e-8  # To prevent log(0)
    prediction = torch.clamp(prediction, epsilon, 1 - epsilon)
    return -(target * torch.log(prediction) + (1 - target) * torch.log(1 - prediction))

In [91]:
loss.backward()

In [99]:
b.grad

tensor(0.9988)

In [103]:
print(w.grad)

tensor(6.6918)


In [105]:
x = torch.tensor([1.0, 2.0, 3.0], requires_grad = True)

In [107]:
x

tensor([1., 2., 3.], requires_grad=True)

In [111]:
y = (x**2).mean()
y

tensor(4.6667, grad_fn=<MeanBackward0>)

In [113]:
y.backward()

In [115]:
x.grad

tensor([0.6667, 1.3333, 2.0000])

In [141]:
x = torch.tensor(2.0, requires_grad = True)
x

tensor(2., requires_grad=True)

In [174]:
y = x**2
y

tensor(4., grad_fn=<PowBackward0>)

In [176]:
y.backward()

In [177]:
x.grad

tensor(4.)

In [182]:
x.grad.zero_()

tensor(0.)

In [186]:
x.requires_grad_(False)
# always close the gradient trackin

tensor(2.)

In [190]:
z = x.detach()
z

tensor(2.)

In [192]:
with torch.no_grad():
    y = x ** 2

In [194]:
y

tensor(4.)

In [196]:
y.bachward()

AttributeError: 'Tensor' object has no attribute 'bachward'